
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[206] =
    {   0,
        2,    2,   22,   21,    3,    2,   21,    3,   21,    7,
       20,   20,   20,   20,   20,   12,   12,   20,   20,   20,
       20,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,    8,
        0,    0,    3,    3,    2,    0,   13,    7,    0,    9,
        7,    7,    8,    4,    5,    0,    0,   12,   12,   15,
        0,    0,   16,   11,   11,   13,    0,   12,   20,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    1,   10,
       10,   10,   10,   10,    1,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    0,    0,   13,

       13,    9,    0,    0,    5,    4,    0,    4,    4,    0,
        4,   12,   12,   11,   11,    0,    0,   18,   14,    0,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    5,    5,
        0,    0,    0,    4,    0,    4,    0,    4,    4,    6,
        4,   11,   11,   18,    0,    0,   17,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    8,    0,    8,    0,    6,    0,    0,    0,
        0,   10,   10,   10,   10,   10,   10,   10,   10,    1,
        0,    0,   17,   10,   10,   10,   10,   10,   10,    0,

       19,   10,   10,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   39,   46,   39,
       47,    1,   48,   49,   50,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   39,
       46,   39,    1,   51,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    2,    3,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[220] =
    {   0,
        0,    0,  309,   45,   52,  297, 1295,   56,   62,  110,
      109,  114,  116,  120,  131,  144,  191,  135,  143,  155,
      159,  242,  146,  151,  153,  175,  176,  161,  193,  190,
      200,  270,  198,  272,  199,  277,  279,  292,  171,  236,
      225,  311,  328,  127,  225,    0,  338,  319,  218,  386,
      393,  397, 1295,  405,  213,  409,  420,  433,   49,  445,
      141,  440,  456,  487,  534,  181,  467,  581,  424,  632,
      301,  445,  469,  447,  470,  484,  489,  483,  491,  492,
      516,  517,  519,  522,  536,  539,  542,  553,  560,  567,
      577,  582,  580,  585,  587,  595,  660,  196,  174,  700,

        0,  196,  682,  560,  690,  749,  188,  757,  765,  238,
      773,  774,  781,    0,  156,  788,  326,  795,  842,  800,
      778,  796,  797,  802,  803,  821,  824,  841,  843,  846,
      848,  849,  863,  854,  871,  872,  880,  873, 1295,  161,
      914,  922,  295,  930,  938,  946,  149,  954,  962,  288,
      970,  818,  971,  978,  989, 1000, 1007,  985,  980,  994,
     1003, 1004, 1011, 1014, 1013, 1021, 1035, 1041, 1032, 1034,
     1049, 1055,  134, 1083,  130, 1093,  126,  449, 1097, 1108,
     1113, 1095, 1103, 1109, 1110, 1120, 1127, 1130, 1128, 1137,
      479, 1168, 1172, 1150, 1157, 1159, 1167, 1170, 1177,   58,

     1208, 1187, 1202, 1196, 1295, 1242, 1246, 1250,   55, 1254,
     1258, 1262, 1266, 1270, 1274, 1278, 1282, 1286, 1290
    } ;

static const flex_int16_t yy_def[220] =
    {   0,
      205,    1,  205,  206,  206,  205,  205,  205,  205,  207,
      208,  206,  208,  206,  206,    9,    9,  206,  206,  206,
      206,  205,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,  206,  209,
      208,  208,  206,  205,  205,    9,  205,  207,  210,  211,
      212,  212,  205,  213,  208,  206,  206,  206,   58,  206,
      205,   58,  206,    9,    9,   47,  206,    9,  206,  205,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,  209,  205,  205,

       47,  210,  211,  210,  212,  213,  214,  215,  213,  208,
      216,   58,   58,   58,   58,  205,  205,   58,   58,  206,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,  205,  210,
      217,  218,  219,  215,  217,  213,  214,  215,  213,  208,
      216,   58,   58,  205,  206,  206,  206,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,  214,  217,  214,  218,  205,  219,  206,  206,
      206,   22,   22,   22,   22,   22,   22,   22,   22,   22,
      214,  206,  206,   22,   22,   22,   22,   22,   22,  205,

      206,   22,   22,   22,    0,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205
    } ;

static const flex_int16_t yy_nxt[1347] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   12,   14,   15,   12,   16,   17,   18,   12,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   28,
       29,   28,   28,   28,   30,   31,   32,   33,   28,   34,
       35,   36,   28,   37,   38,   28,   12,   12,    9,   28,
        4,   40,   41,   43,   42,   98,   44,   44,   40,   41,
       44,   42,   39,   39,   59,   59,  191,   46,   40,   41,
       39,   42,   39,   39,   39,   39,   39,   46,   46,   39,
       39,   39,   39,   39,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   39,   39,
       46,   47,   39,   49,   49,   53,   50,   51,   54,   52,
       40,   41,   53,   42,   55,   42,   40,   41,   44,   42,
       56,   44,   56,   57,  191,   58,   59,   40,   41,  143,
       42,   40,   41,  143,   42,   61,   60,   60,   61,   40,
       41,  116,   42,  116,   62,   69,   62,   63,  143,   64,
       65,   40,   41,   69,   42,   40,   41,  102,   42,   71,
       66,  115,   75,   77,   71,   69,   71,   40,   41,   69,
       42,   71,  139,   99,   71,   76,   71,   78,   71,   79,
       71,  120,   71,  120,   67,   61,   71,  143,   71,   71,

       71,   62,  102,   62,   63,   99,   68,   68,   80,   82,
       81,   71,   83,   71,   71,   71,   71,   66,   84,   53,
       85,   71,   71,   71,  102,   71,   87,   45,   86,   71,
       88,   53,   71,   71,   71,   71,   89,   91,   71,   71,
       93,   67,   39,   39,   53,   99,  145,   39,   40,   41,
       39,   42,   39,   39,   39,   39,   39,   70,   70,   39,
       39,   39,   39,   39,   71,   72,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   73,   71,   71,
       71,   74,   71,   71,   71,   71,   71,   71,   39,   39,
       39,   71,   39,   90,   53,   71,  145,   85,   92,   45,

       71,   95,   71,  177,  178,   71,   94,   71,  205,   85,
      205,   71,   71,   85,   71,   71,   71,   53,   71,   55,
       42,   96,   49,   49,   71,   50,   51,   71,   52,   43,
      117,   97,   44,  205,   40,   41,   71,   42,   39,   39,
       71,  154,  154,   39,   40,   41,   39,   42,   39,   39,
       39,   39,   39,  100,  100,   39,   39,   39,   39,   39,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,   39,   39,   39,  101,   39,   49,
       49,  205,   50,   49,  205,  104,   49,   49,  205,  102,

       49,   49,  205,  102,  205,  105,   52,  107,  107,  107,
      205,  108,  109,  110,  111,   40,   41,  205,   42,   56,
      205,   56,   57,  205,  112,  113,   40,   41,  205,   42,
       40,   41,  205,   42,  205,   60,   60,   61,  205,   40,
       41,  205,   42,   62,  117,   62,   63,  205,  114,  115,
      205,   40,   41,   39,   42,  118,  118,  177,  178,   67,
       60,   60,   40,   41,  205,   42,   39,  205,   71,  205,
       71,  119,  119,   40,   41,  205,   42,  120,  205,  120,
       71,  205,   71,   67,   71,  121,  122,  200,  143,  205,
       39,   61,   71,   71,   85,  205,  205,   62,  123,   62,

       63,  205,   64,   65,   71,   71,   71,   71,   71,   71,
      124,  205,   71,   66,   71,   71,  205,  205,  126,   71,
      205,  205,   71,   71,   71,  205,   71,   71,   71,  125,
       71,   71,  128,  127,  205,  205,  205,   67,   61,   71,
       71,   85,   71,  205,   62,   71,   62,   63,  205,   65,
       65,   71,   71,  129,   71,   71,   71,  130,   85,   71,
       66,   71,   71,  205,  205,   71,  102,   85,  140,  104,
      205,   71,  205,  205,   71,   71,   71,   71,   71,  205,
      131,   71,  205,   71,   67,   61,   85,  205,   71,  205,
       71,   62,   71,   62,   63,   71,   68,   68,  132,   71,

       71,   85,   71,   71,  134,   71,   71,   66,   71,  205,
       71,  136,   71,  133,  205,   71,   71,   71,   71,  135,
       71,   71,   71,  205,   71,  137,   85,  205,  205,  205,
       71,   67,   39,   39,   71,  205,  205,   39,   40,   41,
       39,   42,   39,   39,   39,   39,   39,   70,   70,   39,
       39,   39,   39,   39,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   39,   39,
       39,   70,   39,   71,  205,   49,   49,  205,   50,   49,
      138,  104,  205,   49,   49,   71,  102,  205,  205,   71,

       39,   39,  205,  205,  205,   39,   40,   41,   39,   42,
       39,   39,   39,   39,   39,  100,  100,   39,   39,   39,
       39,   39,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   39,   39,   39,  100,
       39,  107,  107,  107,  205,  108,  205,  141,  142,  107,
      107,  107,  205,  205,  205,  107,  143,  107,  107,  107,
      205,  108,  109,  141,  142,  147,  147,  147,  205,  148,
      149,  150,  151,  205,   39,  205,   39,  205,  205,  152,
      153,   39,  117,   39,  205,  205,  113,  113,  116,  205,

      116,   71,  205,  154,  154,  205,   40,   41,   39,   42,
      118,  118,  205,   71,  158,  157,  157,   71,  159,   71,
       71,   39,  205,  205,  161,   71,   71,  160,   39,   85,
       39,   71,   71,  152,  153,   71,   71,   71,   71,  205,
      205,   71,   71,  205,   71,   39,  205,  164,  205,  205,
      205,  205,  155,  205,  155,   39,   71,  119,  119,   71,
       71,  162,  163,   71,   71,  165,   71,   85,  156,   71,
      166,   71,   71,  205,  167,  168,   71,   71,   71,   85,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
      205,  169,  156,   71,   71,   71,   71,  205,   71,  205,

      205,  170,   71,   71,  205,  205,   71,   85,   71,  205,
       71,   71,   71,  171,  172,   71,  107,  107,  107,   71,
      173,  205,  205,  142,  147,  147,  147,  205,  175,  205,
      150,  176,  107,  107,  107,  205,  205,  205,  107,  143,
      107,  107,  107,  205,  173,  205,  110,  142,  107,  107,
      107,  205,  108,  205,  141,  142,  107,  107,  107,  205,
      205,  205,  107,  143,  107,  107,  107,  205,  108,  109,
      141,  142,  147,  147,  147,  205,  148,  149,  150,  151,
      205,   39,  205,   39,  205,  205,  153,  153,  116,  205,
      116,  205,  205,  154,  154,   40,   41,  205,   42,  179,

      205,  179,  205,   71,  180,  180,   40,   41,   71,   42,
      181,  205,  181,   40,   41,   71,   42,   71,  182,   71,
       71,  205,  157,  157,   71,   85,   71,   71,  205,   85,
      205,  205,  205,   71,   71,   85,   71,   71,   71,   71,
      205,  183,   71,   71,   71,   85,   71,  184,   71,   71,
       71,  205,   71,   71,   85,   71,   71,   71,   71,  205,
       71,  205,  185,  186,   71,  187,  205,   71,  205,  189,
       71,  188,   71,   71,   71,   85,   71,  205,   71,  205,
       71,  190,  205,  205,   71,  107,  107,  107,   71,  173,
       71,  205,  142,  205,   71,  147,  147,  147,  205,  175,

      205,  150,  176,   40,   41,  205,   42,  179,  205,  179,
      205,  205,  180,  180,   40,   41,  205,   42,   71,   40,
       41,  192,   42,  180,  180,  205,   71,  205,  193,  193,
       71,  205,   71,   71,   71,   85,  205,  194,  195,  205,
      196,  205,   71,   71,   71,   71,  197,  205,   71,   71,
       71,   71,  198,   71,  205,   71,   85,  205,  205,   71,
       71,  205,   71,   71,  205,   71,   71,   71,   85,   71,
      199,  205,   71,   71,   40,   41,   71,   42,   40,   41,
       71,   42,   71,  201,  201,   71,  205,  193,  193,   71,
       71,  202,   71,   71,   71,  204,   71,  205,   71,  203,

       71,  205,   71,  205,   85,   71,   85,  205,  205,   71,
       71,  205,   85,   85,   40,   41,   71,   42,  155,   71,
      155,  205,   71,  201,  201,   71,   71,  205,   85,  205,
      205,   85,  205,  205,  205,   71,  205,   71,  205,  205,
      205,   71,   39,  205,  205,   39,   48,  205,   48,   48,
       41,  205,  205,   41,   49,  205,   49,   49,  103,  205,
      103,  103,   51,  205,   51,   51,  106,  106,  106,  106,
      107,  107,  107,  107,  144,  144,  144,  144,  146,  146,
      146,  146,  141,  141,  141,  141,  174,  174,  174,  174,
      147,  147,  147,  147,    3,  205,  205,  205,  205,  205,

      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205
    } ;

static const flex_int16_t yy_chk[1347] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    4,    5,    4,  209,    5,    8,    5,    5,
        8,    5,    9,    9,   59,   59,  200,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,   10,   10,   11,   10,   10,   11,   10,
       12,   12,   13,   12,   13,   13,   14,   14,   44,   14,
       14,   44,   14,   14,  177,   14,   14,   15,   15,  175,
       15,   18,   18,  173,   18,   61,   15,   15,   16,   19,
       19,   61,   19,   61,   16,   18,   16,   16,  147,   16,
       16,   20,   20,   19,   20,   21,   21,  140,   21,   23,
       16,  115,   23,   24,   24,   20,   25,   39,   39,   21,
       39,   23,   99,   99,   28,   23,   24,   24,   25,   25,
       24,   66,   25,   66,   16,   17,   28,  107,   26,   27,

       28,   17,  102,   17,   17,   98,   17,   17,   26,   27,
       26,   27,   27,   30,   26,   27,   29,   17,   27,   55,
       29,   33,   35,   31,   49,   30,   30,   45,   29,   30,
       31,   41,   29,   33,   35,   31,   31,   33,   35,   31,
       35,   17,   22,   22,  110,   40,  110,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   32,  150,   34,  150,   32,   34,    6,

       36,   37,   37,  143,  143,   32,   36,   34,    3,   32,
        0,   34,   36,   36,   37,   38,   36,   42,   37,   42,
       42,   38,   48,   48,   71,   48,   48,   38,   48,   43,
      117,   38,   43,    0,   43,   43,   71,   43,   47,   47,
       71,  117,  117,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   50,
       50,    0,   50,   50,    0,   50,   51,   51,    0,   51,

       52,   52,    0,   52,    0,   52,   52,   54,   54,   54,
        0,   54,   54,   54,   54,   56,   56,    0,   56,   56,
        0,   56,   56,    0,   56,   56,   57,   57,    0,   57,
       69,   69,    0,   69,    0,   57,   57,   58,    0,   58,
       58,    0,   58,   58,   62,   58,   58,    0,   58,   58,
        0,   60,   60,   62,   60,   62,   62,  178,  178,   58,
       60,   60,   63,   63,    0,   63,   62,    0,   72,    0,
       74,   63,   63,   67,   67,    0,   67,   67,    0,   67,
       72,    0,   74,   58,   72,   72,   74,  191,  191,    0,
       62,   64,   73,   75,   73,    0,    0,   64,   75,   64,

       64,    0,   64,   64,   73,   75,   78,   76,   73,   75,
       76,    0,   77,   64,   79,   80,    0,    0,   78,   76,
        0,    0,   78,   76,   77,    0,   79,   80,   77,   77,
       79,   80,   80,   79,    0,    0,    0,   64,   65,   81,
       82,   81,   83,    0,   65,   84,   65,   65,    0,   65,
       65,   81,   82,   82,   83,   81,   82,   84,   83,   85,
       65,   84,   86,    0,    0,   87,  104,   87,  104,  104,
        0,   85,    0,    0,   86,   85,   88,   87,   86,    0,
       86,   87,    0,   89,   65,   68,   88,    0,   88,    0,
       90,   68,   88,   68,   68,   89,   68,   68,   90,   89,

       91,   89,   90,   93,   92,   92,   90,   68,   94,    0,
       95,   94,   91,   91,    0,   93,   91,   92,   96,   93,
       94,   92,   95,    0,   94,   96,   95,    0,    0,    0,
       96,   68,   70,   70,   96,    0,    0,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   97,    0,  103,  103,    0,  103,  103,
       97,  103,    0,  105,  105,   97,  105,    0,    0,   97,

      100,  100,    0,    0,    0,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  106,  106,  106,    0,  106,    0,  106,  106,  108,
      108,  108,    0,    0,    0,  108,  108,  109,  109,  109,
        0,  109,  109,  109,  109,  111,  111,  111,  112,  111,
      111,  111,  111,    0,  112,  113,  112,    0,    0,  112,
      112,  113,  116,  113,    0,    0,  113,  113,  116,  118,

      116,  121,    0,  116,  116,    0,  120,  120,  118,  120,
      118,  118,    0,  121,  121,  120,  120,  121,  122,  122,
      123,  118,  152,    0,  124,  124,  125,  123,  152,  125,
      152,  122,  123,  152,  152,  122,  123,  124,  125,    0,
        0,  124,  125,    0,  126,  118,  119,  127,    0,    0,
        0,    0,  119,    0,  119,  119,  126,  119,  119,  127,
      126,  126,  126,  127,  128,  129,  129,  128,  119,  130,
      130,  131,  132,    0,  131,  132,  128,  134,  129,  134,
      128,  130,  129,  131,  132,  130,  133,  131,  132,  134,
        0,  133,  119,  134,  135,  136,  138,    0,  133,    0,

        0,  135,  133,  137,    0,    0,  135,  136,  138,    0,
      135,  136,  138,  137,  138,  137,  141,  141,  141,  137,
      141,    0,    0,  141,  142,  142,  142,    0,  142,    0,
      142,  142,  144,  144,  144,    0,    0,    0,  144,  144,
      145,  145,  145,    0,  145,    0,  145,  145,  146,  146,
      146,    0,  146,    0,  146,  146,  148,  148,  148,    0,
        0,    0,  148,  148,  149,  149,  149,    0,  149,  149,
      149,  149,  151,  151,  151,  153,  151,  151,  151,  151,
        0,  153,    0,  153,    0,    0,  153,  153,  154,    0,
      154,    0,    0,  154,  154,  155,  155,    0,  155,  155,

        0,  155,    0,  159,  155,  155,  156,  156,  158,  156,
      156,    0,  156,  157,  157,  159,  157,  160,  158,  159,
      158,    0,  157,  157,  158,  159,  161,  162,    0,  160,
        0,    0,    0,  160,  163,  161,  165,  164,  161,  162,
        0,  163,  161,  162,  166,  162,  163,  164,  165,  164,
      163,    0,  165,  164,  165,  169,  166,  170,  167,    0,
      166,    0,  166,  167,  168,  168,    0,  169,    0,  170,
      167,  169,  171,  170,  167,  171,  168,    0,  172,    0,
      168,  172,    0,    0,  171,  174,  174,  174,  171,  174,
      172,    0,  174,    0,  172,  176,  176,  176,    0,  176,

        0,  176,  176,  179,  179,    0,  179,  179,    0,  179,
        0,    0,  179,  179,  180,  180,    0,  180,  182,  181,
      181,  180,  181,  180,  180,    0,  183,    0,  181,  181,
      182,    0,  184,  185,  182,  184,    0,  182,  183,    0,
      185,    0,  183,  186,  184,  185,  186,    0,  184,  185,
      187,  189,  188,  188,    0,  186,  189,    0,    0,  186,
      190,    0,  187,  189,    0,  188,  187,  189,  187,  188,
      190,    0,  190,  194,  192,  192,  190,  192,  193,  193,
      195,  193,  196,  192,  192,  194,    0,  193,  193,  194,
      197,  194,  195,  198,  196,  196,  195,    0,  196,  195,

      199,    0,  197,    0,  198,  198,  197,    0,    0,  198,
      202,    0,  199,  202,  201,  201,  199,  201,  201,  204,
      201,    0,  202,  201,  201,  203,  202,    0,  203,    0,
        0,  204,    0,    0,    0,  204,    0,  203,    0,    0,
        0,  203,  206,    0,    0,  206,  207,    0,  207,  207,
      208,    0,    0,  208,  210,    0,  210,  210,  211,    0,
      211,  211,  212,    0,  212,  212,  213,  213,  213,  213,
      214,  214,  214,  214,  215,  215,  215,  215,  216,  216,
      216,  216,  217,  217,  217,  217,  218,  218,  218,  218,
      219,  219,  219,  219,  205,  205,  205,  205,  205,  205,

      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "test.lex"
#line 2 "test.lex"
#include<stdio.h>
#include<string.h>
#include <ctype.h>

unsigned charCount = 1,lineCount = 1;
void commentL(char *yytext,int lineCount,int charCount)
{
	int str_l = strlen(yytext);
	
	
	printf("Line: %d, 1st char: %d, \"%s\" is a invaild \"commentL\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
void commentR(char *yytext,int lineCount,int charCount)
{
	int str_l = strlen(yytext);
	/*for(int i=0;i<str_l;i++)
	{
		printf("")	
	}*/
	
	printf("Line: %d, 1st char: %d, \"%s\" is a invaild \"commentR\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
void comment(char *yytext,int lineCount,int charCount)
{
	int str_l = strlen(yytext);
	
	
	printf("Line: %d, 1st char: %d, \"%s\" is a \"comment\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
void string(char *yytext,int lineCount,int charCount)
{
	int str_l = strlen(yytext);
	if( str_l > 30)
	{
		printf("Line: %d, 1st char: %d,\"%s\" is a invild \"string(string)\".\n",lineCount,charCount,yytext);
		printf("\033[40;31;5mError :\033[0m\n"); 
		printf("\033[40;31mYour string is wrong ,look for string-(0) : the string is too long , size be in under 30 words.\033[0m\n");
	}
	else
	{
	printf("Line: %d, 1st char: %d, \"%s\" is a \"string(string)\".\n",lineCount,charCount,yytext);
	}	
	lineCount++;charCount = 1;
}
void nostring1(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"string(nostring1)\".\n",lineCount,charCount,yytext);
	printf("\033[40;31;5mError :\033[0m\n"); 
	printf("\033[40;31mYou couldnt forget to set (') afterhand the string what you tpye in .\033[0m\n ");
	lineCount++;charCount = 1;
}
void nostring2(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"string(nostring2)\".\n",lineCount,charCount,yytext);
	printf("\033[40;31;5mError :\033[0m\n"); 
	printf("\033[40;31mError :You couldnt forget to set (') beforehand the string what you tpye in .\033[0m\n ");
	lineCount++;charCount = 1;
}
void id(char *yytext,int lineCount,int charCount)
{
	int str_l = strlen(yytext);
	if( str_l > 15)
		{
		printf("Line: %d,1st char: %d,\" %s \" is a invild \"ID\".\n",lineCount,charCount,yytext);
		printf("\033[40;31;5mError : \033[0m\n");
		printf("\033[40;31mYour ID is wrong ,look for ID-(0) : the ID is too long , size be in under 15 words.\033[0m\n");
		}
	else
	{	
	printf("Line: %d, 1st char: %d, \"%s\" is a \"ID(id)\".\n",lineCount,charCount,yytext);
	}
	lineCount++;charCount = 1;
}
void no_Integer(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"Integer(no_Integer)\".\n",lineCount,charCount,yytext);
	printf("\033[40;31;5mError :\033[0m\n"); 
	printf("\033[40;31mYou shouldnt set '0' in front of the integer with digits , it doesnt make sence.\033[0m\n ");
	lineCount++;charCount = 1;
}
void Integer(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Integer(Integer)\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
/*
void Integeradd(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Integer\".\n",lineCount,charCount,yytext);
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Integeradd\".\n",lineCount,charCount,yytext);
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Integeradd\".\n",lineCount,charCount,yytext);
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Integeradd\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
*/
void Inv_id(char *yytext,int lineCount,int charCount)
{
	//printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"ID\".\n",lineCount,charCount,yytext);
	int str_l = strlen(yytext);
	
	if( str_l > 15)
		{
		printf("Line: %d, 1st char: %d,\" %s \" is a invild \"ID\".\n",lineCount,charCount,yytext);
		printf("\033[40;31;5mError :\033[0m\n"); 
		printf("\033[40;31mYour ID is wrong ,look for ID-(0) : the ID is too long , size be in under 15 words.\033[0m\n");
		}
	else
	{
		if( yytext[0] == '#' || yytext[0] == '^')
			{
			printf("Line: %d, 1st char: %d,\" %s \" is a invild \"ID\".\n",lineCount,charCount,yytext);
			printf("\033[40;31;5mError :\033[0m\n"); 
			printf("\033[40;31mYour ID is wrong ,look for ID-(2) : the head isn't be # or ^ .\033[0m\n");
			}
		else if( (yytext[0] < 'a' || yytext[0] > 'z') && (yytext[0] < 'A' || yytext[0] > 'Z') && ( yytext[0] != '_'))
			{
			printf("Line: %d, 1st char: %d,\" %s \" is a invild \"ID\".\n",lineCount,charCount,yytext);
			printf("\033[40;31;5mError :\033[0m\n"); 
			printf("\033[40;31mYour ID is wrong ,look for ID-(1) : the ID need in a ~ z A ~ Z.\033[0m\n");
			}
		else			
			printf("Line: %d, 1st char: %d,\"%s\" is an \"ID\".\n",lineCount,charCount,yytext);
	}
	
	lineCount++;charCount = 1;
}
void small_2(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Real(small_2)\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
void small(char *yytext,int lineCount,int charCount)
{
	//printf("Line: %d, 1st char: %d, \"%s\" is a \"Real(small)\".\n",lineCount,charCount,yytext);
	int dot=-1;
	int i;
	//printf("\n\ncheck__float\n\n");
	
	int str_l=strlen(yytext);
	char s[str_l];
	strcpy(s,yytext);
	//printf("\nstring is : %s \n",s);
	for(i=0;i<str_l;i++)
		//printf("%c ",s[i]);
	//printf("\nstring long : %d\n\n\n" ,str_l);
	for(i=0;i<str_l;i++)
		if( s[i] == '.')
			{
			//
			dot=i;
			}
	//brfore .
	//for(int i=0;i<str_l;i++)
	if( s[0] == '0')
	{
		if( s[1] != '.')
			{
			printf("Line: %d,1st char: %d, \"%s\" is a invalid \"real(small)\".\n",lineCount,charCount,yytext);
			printf("\033[40;31;5mError :\033[0m\n"); 
			printf("\033[40;31mreal wrong : (1) .\033[0m\n");	
			}	
	}
	/*
	if( s[0]== '0' && ( s[dot] != '0' || s[dot-1] != '.' ) )
		printf(" means  invlid float number. \n\n\n");
	*/
	else if( s[str_l-1] == '0')
	{	
		if( s[str_l-2]== '0' && s[str_l-1]== '0' )
			{
			printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"real(small)\".\n",lineCount,charCount,yytext);
			printf("\033[40;31;5mError :\033[0m\n"); 
			printf("\033[40;31mreal wrong : (2-2) . \033[0m\n");
			}
	}
	else if( s[dot+1] == '\0' && dot != -1 )
		{
		printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"real(small)\".\n",lineCount,charCount,yytext);
		printf("\033[40;31;5mError :\033[0m\n"); 
		printf("\033[40;31mreal wrong : (3) . \033[0m\n");
		}
	else if( s[0] == '.')
		{
		printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"real(small)\".\n",lineCount,charCount,yytext);
		printf("\033[40;31;5mError :\033[0m\n"); 
		printf("\033[40;31mreal wrong : (4) . \033[0m\n");
		}
	else
	printf("Line: %d, 1st char: %d, \"%s\" is a \"real(small)\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
/*
void no_small1(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"Real(no_small1)\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
*/
void no_small2(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"Real(no_small2)\".\n",lineCount,charCount,yytext);
	printf("\033[40;31;5mError :\033[0m\n"); 
	printf("\033[40;31mYou shoudl put integer beforehand the dot(.) .\033[0m\n");
	lineCount++;charCount = 1;
}
void no_small3(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a invalid \"Real(no_small3)\".\n",lineCount,charCount,yytext);
	printf("\033[40;31;5mError :\033[0m\n"); 
	printf("\033[40;31mYou shoudl put integer afterhand the dot(.) .\033[0m\n");
	lineCount++;charCount = 1;
}
void real(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Real(real)\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}
void symint(char *yytext,int lineCount,int charCount)
{
	int str_l = strlen(yytext);
	int i;
	
	//printf("%s",yytext);
	//printf("------\n");
	printf("Line: %d, 1st char: %d, \"",lineCount,charCount);
	for(i=0;i<str_l;i++)	
		{
		if(yytext[i] == '+' || yytext[i] == '-')
			{
			printf("\" is a \"integer(symint)\".\n");
			printf("Line: %d, 1st char: %d, \"%c\" is a \"symreal_2\".\n",lineCount,charCount,yytext[i]);
			charCount++;
			printf("Line: %d, 1st char: %d, \"",lineCount,charCount);
			}
		else			
			{
			printf("%c",yytext[i]);
			charCount++;
			}
		/*
			if(i%2 == 0 )
			{
					printf("Line: %d, 1st char: %d, \"%c\" is a \"Symbol(s+i)\".\n",lineCount,charCount++,yytext[i]);
			}
			else
			{
					printf("Line: %d, 1st char: %d, \"%c\" is a \"Integer(s+i)\".\n",lineCount,charCount++,yytext[i]);
			}
		*/
		}
	printf("\" is a \"integer(symint)\".\n");
	//printf("\n");
	
	
	lineCount++;charCount = 1;
}
void symreal_2(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a \"symreal_2\".\n",lineCount,charCount,yytext);
	int str_l = strlen(yytext);
	for(int i=0;i<str_l;i++)	
		{
		printf("%c",yytext[i]);
		}
	printf("\n");
		
	/*if( yytext[0] == '+' || yytext[0] == '-')
	{
		for(int i=0;i<str_l;i++)	
		{
			if(i%2 == 0 )
			{
					printf("Line: %d, 1st char: %d, \"%c\" is a \"Symbol(s+i)\".\n",lineCount,charCount++,yytext[i]);
			}
			else
			{
					printf("Line: %d, 1st char: %d, \"%c\" is a \"Integer(s+i)\".\n",lineCount,charCount++,yytext[i]);
			}
		}
	}
	else
	{
		for(int i=0;i<str_l;i++)	
		{	
			if(i%2 == 0 )
			{
					printf("Line: %d, 1st char: %d, \"%c\" is a \"Symbol(s+i)\".\n",lineCount,charCount++,yytext[i]);
			}
			else
			{
					printf("Line: %d, 1st char: %d, \"%c\" is a \"Integer(s+i)\".\n",lineCount,charCount++,yytext[i]);	
			}
		}
	}
	*/
	lineCount++;charCount = 1;
}
void symbol2(char *yytext,int lineCount,int charCount)
{
	printf("Line: %d, 1st char: %d, \"%s\" is a \"Symbol\".\n",lineCount,charCount,yytext);
	lineCount++;charCount = 1;
}

#line 1115 "lex.yy.c"
#line 1116 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 338 "test.lex"

#line 1335 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 206 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1295 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 339 "test.lex"
{
printf("Line: %d, 1st char: %d,\"%s\" is a \"reserved_word\".\n",lineCount,charCount,yytext);
charCount+=yyleng;
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 343 "test.lex"
{lineCount++;charCount=1;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 344 "test.lex"
{charCount+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 345 "test.lex"
{commentL(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 346 "test.lex"
{commentR(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 347 "test.lex"
{comment(yytext,lineCount,charCount);charCount+=yyleng;
	int line=0;
	int str_l = strlen(yytext);
	for(int i=0;i<str_l;i++)
	{		
		//printf("%d:-%c-\n",i+1,yytext[i]);	
		//if(yytext[i] == '\r')
			//printf("rrr\n");
		if(yytext[i] == '\n')
			line++;
	}
	lineCount+=line;
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 360 "test.lex"
{nostring1(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 361 "test.lex"
{nostring2(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 362 "test.lex"
{string(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 363 "test.lex"
{id(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 364 "test.lex"
{no_Integer(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 365 "test.lex"
{Integer(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 366 "test.lex"
{Inv_id(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 367 "test.lex"
{small(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 368 "test.lex"
{no_small2(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 369 "test.lex"
{no_small3(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 370 "test.lex"
{real(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 371 "test.lex"
{symint(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 372 "test.lex"
{symreal_2(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 373 "test.lex"
{symbol2(yytext,lineCount,charCount);charCount+=yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 374 "test.lex"
ECHO;
	YY_BREAK
#line 1514 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 206 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 206 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 205);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 374 "test.lex"


int main()
{
	yylex();		
	printf("\n\nThe number of characters: %d\n",charCount);
	printf("The number of lines: %d\n", lineCount--);
	return 0;
}

//alpha           [A-Za-z] just for elemnts don't need rules
//{digit}       {printf("digit        \t -%s- \n",yytext);}just for elemnts don't need rules

//{Integeradd}  {Integeradd(yytext,lineCount,charCount);charCount+=yyleng;} not very need to ues
//{small_2}     {small_2(yytext,lineCount,charCount);charCount+=yyleng;} stuck
//{no_small1}	  {no_small1(yytext,lineCount,charCount);charCount+=yyleng;}
void check_comment_one(char *s)
{	
	//printf("stw\t");
	//printf("%s",s);
	printf("\n-----------\n");
	printf("\ncomment : %s\n",s);
	printf("\nlineCount : %d",lineCount);
	printf("\ncharCount : %d",charCount);
	printf("\n-----------\n");
	
	int flag=0;
	int str_l = strlen(s);
	for(int i=0;i<str_l;i++)
		if(s[i] == '*' && s[i+1] == ')'  || s[i] == '(' && s[i+1] == '*')
		{
			flag++;
			//printf("change\n");
			/*for(int j=i;j<str_l;j++)
			{
				if(s[i] == '*' && s[i+1] == ')'  || s[i] == '(' && s[i+1] == '*')
				flag = 1;
			}
			*/
			//printf("\n");
			//printf("\(*");
			//printf("\n");
			
		}
	if( flag%2 != 0)
		{
		printf("flag %d",flag);
		//printf("wrong commoent\n");
		printf("Line: %d, 1st char: %d,\" %s \" is a \"\033[40;31;5mwrong one line comment\033[0m\".\n",lineCount,charCount,yytext);
		charCount = 1;
		}
	else if ( flag%2 == 0)
		{
		//printf("flag %d",flag);
		//printf("correct commnet\n");
		printf("Line: %d, 1st char: %d,\" %s \" is a \" (one line) comment\".\n",lineCount,charCount,yytext);
		charCount = 1;
		}
}
void check_comment(char *s)
{	
	//printf("stw\t");
	//printf("%s",s);
	int flag=0;
	int str_l = strlen(s);
	for(int i=0;i<str_l;i++)
		if(s[i] == '*' && s[i+1] == ')'  || s[i] == '(' && s[i+1] == '*')
		{
			flag++;
			//printf("change\n");
			/*for(int j=i;j<str_l;j++)
			{
				if(s[i] == '*' && s[i+1] == ')'  || s[i] == '(' && s[i+1] == '*')
				flag = 1;
			}
			*/
			//printf("\n");
			//printf("\(*");
			//printf("\n");
			
		}
	if( flag%2 != 0)
		{
		printf("flag %d",flag);
		//printf("wrong commoent\n");
		printf("Line: %d, 1st char: %d, \"%s\" is a \"wrong muti line comment\".\n",lineCount,charCount,yytext);lineCount++;charCount = 1;
		}
	else if ( flag%2 == 0)
		{
		//printf("flag %d",flag);
		//printf("correct commnet\n");
		printf("Line:%d,1st char:%d,\" %s \" is a \"(muti) comment\".\n",lineCount,charCount,yytext);lineCount++;charCount = 1;
		}

}


void string_count(char *s,int lineCount,int charCount)
{	
	printf("\n-----------\n");
	printf("\nstring fuction: %s\n",s);
	printf("\nlineCount : %d",lineCount);
	printf("\ncharCount : %d",charCount);
	printf("\n-----------\n");
	//int n=0;
	//printf("\n\n%s\n\n",s);
	int str_l = strlen(s);
	/*
	for(int i=0;i<str_l;i++)	
		{
			if(s[i] == '\'' && s[i+1] == '\'' && s[i+2] == '\'')
			{				
				printf("\nthere ''' invalid string.\n");
			}
		}
		
	*/
	printf("Line:%d,1st char:%d,\" %s \" is a \"string\".\n",lineCount,charCount,yytext);
	
	if( str_l > 30)
		printf("Line:%d,1st char:%d,\" %s \" is a invild \"string\".\n",lineCount,charCount,s);
	else
	{
	/*
	for(int i=0;i<str_l;i++)	
		{
			if(s[i] == '\'' && s[i+1] == '\'')
			{
				
				for(int j=i;j<str_l;j++)
					{
					s[j]=s[j+1];
					//printf("\n%c",s[j]);
					//printf("%d",str_l);
					}
					
					s[str_l]='\0';				
			}
		}
	*/
	//printf("\ntest 1 : %d,  %d  ,%s  \"string\" \n" , lineCount,charCount+1,yytext);
	//printf("Line:%d,1st char:%d",lineCount,charCount);
	printf("Line:%d,1st char:%d,\" %s \" is a \"string\".\n",lineCount,charCount,s);
	//printf(" Line: %d, 1st char:  %d  ,%s  is a invild \"string\" " , lineCount,charCount+1,yytext);
	}
	
	printf("\nhello2\n");
}

